name: ci
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true            
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache CMake deps
        uses: actions/cache@v4
        with:
          path: |
            build/_deps
            ~/.cache/ccache
            ~/.ccache
            ~/.config/ccache
          key: ${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: ${{ runner.os }}-

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true
          ninja: true
          ccache: true

      - name: Build
        run: cmake -S . -B build -G Ninja && cmake --build build

      - name: Run tests      
        run: cd build && ctest
