name: ci
on:
  pull_request:
    branches:
      - main
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true            
jobs:  
  Test:
    strategy:
      fail-fast: true
      matrix: 
        os: [ubuntu-latest]
        compiler: [llvm, gcc]
        include:
          - os: windows-latest
            compiler: msvc
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v5

      - name: Cache CMake deps
        uses: actions/cache@v4
        with:
          path: |
            build/_deps
            ~/.cache/ccache
            ~/.ccache
            ~/.config/ccache
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: ${{ runner.os }}-${{ matrix.compiler }}-

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{matrix.compiler}}
          cmake: true
          ninja: true
          ccache: true

      - name: Build
        run: cmake -S . -B build -G Ninja && cmake --build build

      - name: Run tests      
        run: cd build && ctest
